# Generated by Django 5.1.1 on 2024-09-23 14:32

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[users.models.validate_image])),
                ('location', models.CharField(max_length=100)),
                ('daily_schedule', models.CharField(max_length=255, verbose_name='What is your daily schedule like?')),
                ('early_riser_night_owl', models.CharField(choices=[('early_riser', 'Early Riser'), ('night_owl', 'Night Owl')], max_length=50, verbose_name='Are you an early riser or a night owl?')),
                ('work_location', models.CharField(choices=[('home', 'Work from Home'), ('out_of_house', 'Out of the House')], max_length=50, verbose_name='Do you work from home, or will you be out of the house most of the time?')),
                ('weekend_activities', models.CharField(max_length=255, verbose_name='How do you spend your weekends?')),
                ('cleaning_schedule_preference', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50, verbose_name='Do you prefer a cleaning schedule?')),
                ('importance_of_tidiness', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='How important is keeping common areas tidy to you? (1-5)')),
                ('clean_up_frequency', models.CharField(choices=[('immediately', 'Immediately'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=50, verbose_name='How often do you clean up after yourself, especially in shared spaces?')),
                ('guest_frequency', models.CharField(choices=[('often', 'Often'), ('sometimes', 'Sometimes'), ('rarely', 'Rarely')], max_length=50, verbose_name='Do you plan to have friends or family over often?')),
                ('preference_for_guests', models.CharField(choices=[('comfortable', 'Comfortable'), ('neutral', 'Neutral'), ('uncomfortable', 'Uncomfortable')], max_length=50, verbose_name='How do you feel about guests?')),
                ('handling_conflict', models.TextField(verbose_name='How do you handle conflict or disagreements with roommates?')),
                ('noise_tolerance', models.CharField(choices=[('quiet', 'Quiet'), ('moderate', 'Moderate'), ('loud', 'Loud')], max_length=50, verbose_name='How do you feel about noise levels, like music or TV in common areas?')),
                ('alone_vs_socializing_time', models.TextField(verbose_name='How much time do you like to spend alone versus socializing?')),
                ('personal_space_expectations', models.TextField(verbose_name='What are your expectations around personal space and privacy?')),
                ('rent_utilities_affordability', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50, verbose_name='Can you comfortably afford rent and utilities?')),
                ('proof_of_income_willingness', models.BooleanField(default=False, verbose_name='Are you willing to share proof of income if needed?')),
                ('bill_splitting_preference', models.CharField(choices=[('equal', 'Split Equally'), ('other', 'Other Arrangement')], max_length=50, verbose_name='Are you open to splitting bills equally?')),
                ('handling_unexpected_costs', models.TextField(verbose_name='How do you handle unexpected costs, like repairs or shared purchases?')),
                ('has_pets', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50, verbose_name='Do you have any pets, or are you planning to get one?')),
                ('pet_tolerance', models.CharField(choices=[('okay', 'Okay with pets'), ('not_okay', 'Not okay with pets')], max_length=50, verbose_name='Are you okay with living with someone who has pets?')),
                ('pet_allergies', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50, verbose_name='Do you have any allergies or concerns about pets in the apartment?')),
                ('smoking_habits', models.CharField(choices=[('smoker', 'Smoker'), ('non_smoker', 'Non-Smoker')], max_length=50, verbose_name='Do you smoke, or do you mind if others do?')),
                ('drinking_habits', models.TextField(verbose_name='How often do you drink, and do you prefer a party-friendly or low-key living environment?')),
                ('hobbies_interests', models.TextField(verbose_name='Do you have any hobbies or interests that might affect living together?')),
                ('friendship_preference', models.CharField(choices=[('friend', 'Looking for a Friend'), ('independent', 'Prefer Keeping to Myself')], max_length=50, verbose_name='Are you looking for a roommate who is more of a friend or someone who keeps to themselves?')),
                ('house_rules', models.TextField(verbose_name="Do you have any specific house rules or boundaries you'd like to establish?")),
                ('grocery_shopping_preference', models.CharField(choices=[('separately', 'Separately'), ('together', 'Together')], max_length=50, verbose_name='How do you handle grocery shopping?')),
                ('shared_space_decoration', models.TextField(verbose_name='How do you feel about decorating or arranging shared spaces?')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100, verbose_name='What is your gender?')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='What is your Age?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
